# -*- coding: utf-8 -*-
"""market_basket.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tze_4RShDw4yJujR-3RBQCuWF8t6W5-9
"""

# Apriori API code from http://rasbt.github.io/mlxtend/user_guide/frequent_patterns/apriori/
# Data from https://grouplens.org/datasets/movielens/100k/

import pandas as pd
import numpy as np

columns = ['user_id', 'item_id', 'rating', 'timestamp']
df = pd.read_csv('./u.data', sep='\t', names=columns)
columns = ['item_id', 'movie title', 'release date', 'video release date', 'IMDb URL', 'unknown', 'Action', 'Adventure',
          'Animation', 'Childrens', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror',
          'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
movies = pd.read_csv('./u.item', sep='|', names=columns, encoding='latin-1')
movie_names = movies[['item_id', 'movie title']]

combined_movies_data = pd.merge(df, movie_names, on='item_id')
combined_movies_data = combined_movies_data[['user_id','movie title']]
combined_movies_data.head()

onehot = combined_movies_data.pivot_table(index='user_id', columns='movie title', aggfunc=len, fill_value=0)
onehot = onehot>0

onehot

from mlxtend.frequent_patterns import apriori

frequent_itemsets = apriori(onehot, min_support=0.3, use_colnames=True)
frequent_itemsets.sort_values(by = "support", inplace= True, ascending = False)
frequent_itemsets

from mlxtend.frequent_patterns import association_rules

rules = association_rules(frequent_itemsets, metric = "confidence", min_threshold = .5).sort_values(by = "confidence")
rules

"""The rule with highest conviction were Star War (1977) -> Raiders of the Lost Ark & Empire Strikes Back. This makes sense since Empire Strikes Back is part of the Star Wars series. The table above was sorted by confidence. Other rules with high confidence have Star Wars as well, where Return of the Jedi (also Star Wars) indicates that the user also watched Star Wars. This is likely partly due to the high count of people who watched Star Wars in the dataset."""

onehot['Star Wars (1977)'].value_counts()